### ISSUE TITLE
Installation Failing

### ISSUE THREAD

**Issue by seppemarotta** [medlmobileenterprises/react-native-wowza-gocoder#14]
I've been following the tutorial , however im unable to make it run on android .

I've tried both manual and automatic installation , adding the sdk to the libs folder in both cases .

I'm having this error : 

<img width="728" alt="screen shot 2017-07-13 at 1 07 35 pm" src="https://user-images.githubusercontent.com/3663789/28181027-bcefb378-67cc-11e7-8c20-194b638966e9.png">

I don't know what im doing wrong in order to make it work.

**Comment by hugo-ns** [comment]
Hi there,
In order to run on Android, you'll need to add the SDK in two places as is specified in the instructions below.

![screen shot 2017-07-14 at 4 28 00 pm](https://user-images.githubusercontent.com/20076751/28234149-74faa81c-68b1-11e7-97d8-2da5a8e78d0c.png)


Let me know if that works for you.
-Thanks

**Comment by dinhtu0802** [comment]
hi @hugomedl 
i try do that but still error here 
<img width="923" alt="screen shot 2018-07-10 at 2 25 24 pm" src="https://user-images.githubusercontent.com/40747369/42495413-35d25d48-844d-11e8-9eb3-30db4fc96baf.png">
Can u help me this problem? Thank you

**Comment by hugo-ns** [comment]
@dinhtu0802 could you share the gradle files of your main app and the one inside the /node-modules/react-native-wowza-gocoder/android?

**Comment by dinhtu0802** [comment]
hi @hugomedl,
<img width="635" alt="screen shot 2018-07-11 at 9 23 26 am" src="https://user-images.githubusercontent.com/40747369/42547432-47422c12-84ec-11e8-88a8-14693907abb9.png">
this is gradle files. How i can fix? Please help me. Thank you
