### ISSUE TITLE
BroadcastView not updating from state

### ISSUE THREAD

**Issue by seppemarotta** [medlmobileenterprises/react-native-wowza-gocoder#17]
I'm working on an app witch request it's configs via http request. Once i have my state updated , i start my stream as usual, however i can never make it work because BroadcastView seems to be working with the starting state values. 
I've also tested this view using the values that are coming from my http request and the streaming is working fine.(Setting up my streaming configs on starting state ) I'm also printing my states value before/after the updates and both are working as expected. 

i've been trying to find a workarround this days, however im unable to solve it and i dont know how to fix this issue. This is my Broadcast View : 

```
                  <BroadcastView
                    style={styles.contentArea}
                    hostAddress={this.state.hostAddress}
                    applicationName={this.state.applicationName}
                    sdkLicenseKey={'GOSK-ED43-0103-F845-460B-XXXX'}
                    broadcastName={this.state.streamName}
                    username={this.state.username}
                    password={this.state.password}
                    backgroundMode={false}
                    sizePreset={2}
                    port={1935}
                    broadcasting={this.state.broadcasting}
                    onBroadcastStart={this._didStartBroadcast}
                    onBroadcastFail={this._broadcastDidFailToStart}
                    onBroadcastStatusChange={this._broadcastStatusDidChange}
                    onBroadcastEventReceive={this._broadcastDidReceiveEvent}
                    onBroadcastErrorReceive={this._broadcastDidReceiveError}
                    onBroadcastVideoEncoded={this._broadcastVideoFrameEncoded}
                    onBroadcastStop={this._didStopBroadcast}
                   />
```

This is the way the request it's done 
```

fetch(finalurl2, {
                                method: 'POST',
                                headers: {
                                            'Accept': 'application/json',
                                            'Content-Type': 'application/json',        
                                },})
                                .then((response) => response.json())
                                .then((response) => {
                                    //If response is true
                                    
                                     
                                    console.log("Stream Antes");
                                    console.log(this.state.stream);

                                    this.setState({
                                            hostAddress: response1.primary_server,
                                            applicationName: response1.application,
                                            username: response1.username,
                                            streamName: response1.primstream_nameary_server,
                                            password: response1.password,
                                        });
                                    

                                   
                                      
                                    var timeoutId = BackgroundTimer.setTimeout(() => {
                                        console.log("tac");
                                        this.props.startBroadcast();
                                        this.setState({broadcasting: !this.state.broadcasting,timeoutId:timeoutId});
                                        // Cancel the timeout if necessary
                                        BackgroundTimer.clearTimeout(this.state.timeoutId);
                                    }, 30000);

                                })
                                .catch((error) => {
                                    console.error(error);
                                });
                            // 
                    })
                    .catch((error) => {
                        console.error(error);
                    });
```

**Comment by JesseDunlap** [comment]
Could this be related to #13? I know certain properties about the broadcast are only set once on initialization, and don't actually update if modified after the initial mount.

**Comment by seppemarotta** [comment]
I think that's the issue , i'm kind of new , do you know how can i pull that fix into my end ? I think i will need to fix streamAddress too, but i might check the SDK and maybe add this feature to the repo.

**Comment by JesseDunlap** [comment]
So as part of this commit: d62077931593759800c4e1833822c43ae82f8376 the broadcast name was made "dynamic" in that it updates the underlying GoCoder component when the `broadcastName` property changed. As long as you're running the latest version of the library, that should be available to you. Unfortunately, to get the additional properties you're updating to work, additional changes will be necessary. You may want to fork the repo and emulate the changes in that commit to get the library working for you.

**Comment by seppemarotta** [comment]
@JesseDunlap i'll try to add this features , so the component can be reloaded if state changes : 
  

> hostAddress={this.state.hostAddress}
>                     applicationName={this.state.applicationName}
>                     sdkLicenseKey={'GOSK-ED43-0103-F845-460B-XXXX'}
>                     broadcastName={this.state.streamName}
>                     username={this.state.username}
>                     password={this.state.password}
