### ISSUE TITLE
GoCoder frame doesn't update when device orientation changes

### ISSUE THREAD

**Issue by JesseDunlap** [medlmobileenterprises/react-native-wowza-gocoder#18]
This might not be the best place to post this, but I am seeing an issue with using GoCoder where the camera frame is not updated when the device rotates. Some research I've done suggests that this might be an issue with GoCoder itself, and not this react-native wrapper, but I wanted to confirm this with the developers of this project before I investigated further. Does anyone support rotating the device during broadcast, and if so, how have you handled this?

Thanks!

**Comment by bendellarocco** [comment]
+1 I cant seem to get mine to be anything but landscape

**Comment by landonalder** [comment]
@JesseDunlap  @bendellarocco  This PR allows you to set an explicit orientation, and if you don't set an orientation, should make the stream match the orientation the device was in when it started.

Once you start a stream, the orientation of the video stream can not change (AFAIK), so if you flip your device, the video stream will retain the original orientation as when it started, but will show the transmitted video in the orientation the device is currently in, with letterboxing.

https://github.com/medlmobileenterprises/react-native-wowza-gocoder/pull/27
