### ISSUE TITLE
Build fails on android

### ISSUE THREAD

**Issue by SharanyaRao91** [medlmobileenterprises/react-native-wowza-gocoder#19]
Android build fails after installing Wowza GoCoder with following error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-wowza-gocoder'.
      > Could not resolve all dependencies for configuration ':react-native-wowza-gocoder:_debugPublishCopy'.
         > Could not find com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0.
           Required by:
               ------Project:react-native-wowza-gocoder:unspecified

RN version - 0.44

Please advice

**Comment by lasuax** [comment]
Same here. I don't think there's a working wowza sdk besides native ones.

**Comment by SharanyaRao91** [comment]
It is working for me now after quite a struggle. The installation steps given here is a mess. Follow below - 

Android

1. Open up android/app/src/main/java/[...]/MainApplication.java
2. Add import com.rngocoder.RNWowzaBroadcasterPackage; to the imports at the top of the file
3. Add new RNWowzaBroadcasterPackage() to the list returned by the getPackages() method
4. Append the following lines to android/settings.gradle:
include ':react-native-wowza-gocoder'
project(':react-native-wowza-gocoder').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-wowza-gocoder/android')
5. Insert the following lines inside the dependencies block in android/app/build.gradle:
  compile project(':react-native-wowza-gocoder')

Post installation Android

1. After obtaining WowzaGoCoderSDK aar file, add it to your **nodemodules/react-native-wowza-gocoder/android/libs** (create libs if needed), it's also need to add the dependency on your main app, add the aar file to libs directory(create it if needed) -> **<ProjectPath>/android/app/libs**
2.Then add the following lines to both build.gradle files, on nodemodules/react-native-wowza-gocoder and app/build.gradle
    repositories {
        flatDir {
            dirs 'libs'
        }
    }
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
    
        // The GoCoder SDK library dependency declaration
        compile 'com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0@aar'
    
        // List additional dependencies here...
    
    }
3. http://www.wowza.com/resources/gocodersdk/docs/1.0/intro-installation/

**Comment by dinhtu0802** [comment]
hi @SharanyaRao91 ,
I try do that but still error here 
<img width="923" alt="screen shot 2018-07-10 at 2 25 24 pm" src="https://user-images.githubusercontent.com/40747369/42496098-3844398c-844f-11e8-8c34-fee497fdcd39.png">
Can u help me?

**Comment by 2chaines** [comment]
@SharanyaRao91 I know this is an older issue, but I don't understand the steps to install. Would this mean that you would check your node module changes into your version control?
