### ISSUE TITLE
CameraFocusMode

### ISSUE THREAD

**Issue by lasuax** [medlmobileenterprises/react-native-wowza-gocoder#22]
According to Wowza SDK documentation (http://www.wowza.com/resources/gocodersdk/docs/1.0/api-docs-ios/WZCamera_h/Classes/WZCamera/#//apple_ref/doc/title:tdef/WZCamera/WZCameraFocusMode) the camera can have a focus mode. All devices I test (Galaxy J5, Zenfone 2, iPhone 5S) have really blurry screen when I use the rear camera. Front cam depends on the device and it can be considered OK but the rear cam must be re-orientated. How can we set this property in our needs?

**Comment by lasuax** [comment]
I've managed it done by manipulating BroadcastView.java and can make a PR upon request.

**Comment by hugo-ns** [comment]
@lasuax please, send the PR.
I'd be happy to take a look it.

**Comment by lasuax** [comment]
@hugomedl PR is ready.

**Comment by lasuax** [comment]
Closing the issue as new PR solves the problem.
