### ISSUE TITLE
Play (view) live stream

### ISSUE THREAD

**Issue by ghost** [medlmobileenterprises/react-native-wowza-gocoder#33]
Hi,

Great project! Stable and easy to integrate..
This might not be the best place to post this, but i can see only broadcast module available. Any plans to introduce the player module to pull/view active stream from wowza?

or is it already available?

Thank you,
Raj

**Comment by hugo-ns** [comment]
Hi Raj,

Unfortunately we don't support the playback feature from GoCoder yet. We're planning to add support for it. we'll keep you posted.

Thanks, 
Hugo
