### ISSUE TITLE
'WowzaGoCoder.h' file not found

### ISSUE THREAD

**Issue by bendellarocco** [medlmobileenterprises/react-native-wowza-gocoder#5]
I am trying to install your iOS sdk.  Your instructions state that react-native link is "Mostly automatic".  Which other steps do I have to do that are not automatic?

Error: 'WowzaGoCoder.h' file not found

Thank you

**Comment by medlmichael** [comment]
Hi Ben,

The Post Installation instructions should be what you need.

Post installation iOS

After obtaining WowzaGoCoderSDK framework and the wowzastatic-lib, add them both to a folder in the root directory of the project.
Add the WowzaGoCoderSDK.framework to the build phases for your app target, add a copy files phase with the WowzaGoCoder.SDK http://www.wowza.com/resources/gocodersdk/docs/1.0/intro-installation/

**Comment by bendellarocco** [comment]
I have now imported the .framkework and the lib folder.  I added the .framework to the build phases as required.  Should I be adding the WowzaGoCoder.SDK file as a  an item in Copy Build Resources?  When I do this I receive this error.

`dyld: Library not loaded: @rpath/WowzaGoCoderSDK.framework/WowzaGoCoderSDK
  Referenced from: /Users/bdellarocco/Library/Developer/CoreSimulator/Devices/155BA978-A27E-471E-8102-AB28F0E51412/data/Containers/Bundle/Application/47BA42FE-67E2-4ADE-B696-7AA5B01C350D/App.app/App
  Reason: image not found
(lldb) `

**Comment by bendellarocco** [comment]
<img width="254" alt="screen shot 2017-05-03 at 1 54 19 pm" src="https://cloud.githubusercontent.com/assets/9866222/25674256/2ca16dd0-3008-11e7-8566-7ead47852849.png">
<img width="814" alt="screen shot 2017-05-03 at 1 54 37 pm" src="https://cloud.githubusercontent.com/assets/9866222/25674257/2e6ae6be-3008-11e7-9dce-e789e12e3a60.png">
<img width="843" alt="screen shot 2017-05-03 at 1 56 49 pm" src="https://cloud.githubusercontent.com/assets/9866222/25674312/60c29e2c-3008-11e7-8308-6ca55d5f0b2d.png">

**Comment by medlmichael** [comment]
When you add them to the root, you are only adding them to the ios folder that is created by react native.  The same folder as your xcode project file.  Once they are added you only need to add the WowzaGoCoderSDK.framework to the Frameworks within XCode.  The folder wowzagodcoder_static_lib should not be added to XCode.  

The attached screenshots should point you in the right direction regarding what files should be there.  Hope you get this worked out.

![screen shot 2017-05-03 at 12 06 16 pm](https://cloud.githubusercontent.com/assets/18446649/25677142/b2c3e726-2ff9-11e7-9116-2fb5f0985949.png)
<img width="260" alt="screen shot 2017-05-03 at 12 10 21 pm" src="https://cloud.githubusercontent.com/assets/18446649/25677143/b2c5a9c6-2ff9-11e7-81a5-1fe66e8ef338.png">
<img width="882" alt="screen shot 2017-05-03 at 12 10 38 pm" src="https://cloud.githubusercontent.com/assets/18446649/25677144/b2c7bf04-2ff9-11e7-83ce-9e1f56ef068a.png">
Thank you,

- Michael

**Comment by bendellarocco** [comment]
That worked perfectly.  Thank you for your help!
