### ISSUE TITLE
Permission Camera

### ISSUE THREAD

**Issue by mucasali** [medlmobileenterprises/react-native-wowza-gocoder#6]
Hi,

i am run your android example, in react-native i not find some error, but the camera cant show. i try to see log in Android Studio, and i find this error,

E/CameraService: Permission Denial: can't use the camera pid=14284, uid=10173

how can i resolve my problem??

Thanks,

**Comment by hugo-ns** [comment]
Hi @mucasali.

You'll need to add these lines to your android manifest file:

`    
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
`

Thank you,
Hugo

**Comment by mucasali** [comment]
Hi @hugomedl,

I have put user prmission in my android manifest, but camera still cant show, in my case i using sdkversion 23, i thing its because android need permission progamaticly like [this](http://stackoverflow.com/questions/37458157/error-failed-to-connect-to-camera-service-android-marshmallow)

i can acces camera after add permission progamaticly in onHostResume (BroadcastView.java),
`

    @Override
    public void onHostResume() {

        permissionCamera();

        if(goCoder == null && cameraView != null) {
            goCoder = BroadcastManager.initBroadcast(localContext, getHostAddress(), getApplicationName(), getBroadcastName(), getSdkLicenseKey(), getUsername(), getPassword(), getSizePreset(), cameraView);

        }

    }

    private void permissionCamera(){
        mActivity = localContext.getCurrentActivity();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            mPermissionsGranted = hasPermissions(localContext, mRequiredPermissions);
            if (!mPermissionsGranted)
                ActivityCompat.requestPermissions(mActivity, mRequiredPermissions, PERMISSIONS_REQUEST_CODE);
        } else
            mPermissionsGranted = true;

        // Start the camera preview display
        if (mPermissionsGranted && cameraView != null) {
            if (cameraView.isPreviewPaused())
                cameraView.onResume();
            else
                cameraView.startPreview();
        }
    }

    //
    // Utility method to check the status of a permissions request for an array of permission identifiers
    //
    private static boolean hasPermissions(Context context, String[] permissions) {
        for(String permission : permissions)
            if (context.checkCallingOrSelfPermission(permission) != PackageManager.PERMISSION_GRANTED)
                return false;

        return true;
    }
`
but the camera show after i reload in debugApp, CMIIW, can you help me to solve my problem??

Thanks,.
Mucasali

**Comment by hugo-ns** [comment]
Hi @mucasali,

Because the BroadcastView is a FrameLayout rather than and Activity, we are not able to get the callback for onRequestPermissionsResult when the permission is granted to start the camera, that's the reason you can only see the camera after reloading. 

Instead you can use the package called "react-native-permissions" to handle the permission prior rendering the BroadcastView.js. 

I updated the sample app, with an example of permissions logic. Please check it out.
In summary you can have a boolean on state to check if the permissions have been granted, and render the BroadcastView accordingly.

`

    const Permissions = require('react-native-permissions'); 
    this.state = {permissionGranted:false};

    function componentDidMount()
    {
      Permissions.checkMultiplePermissions(['camera', 'microphone']).then((response) =>
     {
      const permissionGranted = (response.camera === 'authorized' && response.microphone === 'authorized');
        if(!permissionGranted){
          this.requestPermissions();
        }
        this.setState({permissionGranted:permissionGranted});
      });}

     _requestPermissions() {
      let cameraPermission = false;
      let microphonePermission = false;
      Permissions.requestPermission("camera").then(response => {
        if(response === 'authorized'){
          cameraPermission = true
        }
        Permissions.requestPermission("microphone").then(resp => {
          if (resp === "authorized"){
            microphonePermission = true
          }
          if(!(cameraPermission && microphonePermission)){
             //alert user 
          }
          this.setState({
            permissionGranted:(cameraPermission && microphonePermission)
          })
        })
      })
    }
    render() {
      if(!this.state.permissionGranted){
        return(<View style={{backgroundColor:'black'}}>
            </View>
          )
      }
      return (
        <View style={styles.container}>
          <BroadcastView style={styles.contentArea}
                         hostAddress={config.hostAddress}
        </BroadcastView>
  }
 
`





Let me know how it works for you

**Comment by mucasali** [comment]
Hi @hugomedl , 

this work in my device,. Thanks alot for your guide,.
