### ISSUE TITLE
'WowzaGoCoder.h' file not found

### ISSUE THREAD

**Issue by kelvinaliyanto** [medlmobileenterprises/react-native-wowza-gocoder#8]
Hi, I am trying to use this project to stream, but when I add the WowzaGoCoderSDK and try building and I got this error.

> /Users/valleyreign/VideoStream/node_modules/react-native-wowza-gocoder/ios/WMBroadcastViewDelegate.h:10:9: 'WowzaGoCoder.h' file not found

Can anyone advise on this matter?

**Comment by hugo-ns** [comment]
Duplicate issue #5
